[package]
name = "sandpost-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rusqlite.workspace = true
serde.workspace = true
thiserror.workspace = true
sandpost-core.workspace = true

[dev-dependencies]
serde_json.workspace = true
