[package]
name = "sandpost-mail"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mail-parser.workspace = true
sha2.workspace = true
sandpost-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
